### ISSUE TITLE
Add config for caching files depending on Symfony environment

### ISSUE THREAD

**Issue by mtarld** [mtarld/symbok-bundle#6]
Add configuration in order to enable/disable class compilation caching depending on Symfony environment:
Something like:
```yml
cache:
    env:
        prod: true
        dev: true
        test: false
```
